### ISSUE TITLE
isotope

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite#17]
soyons fous : utiliser isotope et/ou masonry (ou équivalent plus libre ?) pour sélectionner nos vignettes

**Comment by brunob** [comment]
Si c'est pour l'affichage des grilles de medias, ça n'a pas sa place dans geodiv par défaut, et ça peut être fait très facilement avec peu de surcharge, et surtout sans js cf https://www.smashingmagazine.com/native-css-masonry-layout-css-grid/ & https://seenthis.net/messages/775950 & https://seenthis.net/messages/855086
