### ISSUE TITLE
associer un kml à catégorie ou collection

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite#19]
Je jette ici une idée à préciser, ce n'est peut-être pas le meilleur lieu pour cela.

L'idée est de considérer des "territoires", définis par (ou avec) un kml, en tout cas un polygône de points.

Aujourd'hui, on peut afficher des kmls, qui sont considérés comme un media (et donc apparaît dans la liste des medias, et a un point sur la carte). 
Je souhaiterais afficher un kml non pas comme un media, mais comme représentant une catégorie, ou une collection (je ne sais pas ce qui serait le mieux, mais possiblement les 2).
On pourrait alors trouver (avec geophp?) tous les médias inclus (ou proches) de cette catégorie/collection.

Je peux aussi ajouter un champ extra "kml" aux catégories.
On pourrait aussi choisir d'afficher ou non ces kmls avec une couleur de fond ou juste le contour.

**Comment by brunob** [comment]
C'est bien l'usage du plugin https://github.com/geodiversite/geodiversite_balades qui permet de lier un objet GIS à une collection (et donc d'importer un kml ou gpx lors de la création de la collection). Et sinon, ta demande ressemble fortement à un doublon de https://github.com/geodiversite/geodiversite/issues/9 ;)

**Comment by ubiquando** [comment]
En effet, ça ressemble beaucoup au #9

**Comment by brunob** [comment]
Parfait, on ferme ici alors.
