### ISSUE TITLE
multidomaines

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite#20]
j'ai testé et pas (encore) réussi à utiliser le plugin multidomaines pour rediriger un sous-domaine vers une page catégorie...

**Comment by brunob** [comment]
On sort complètement du cadre de geodiv là, HS donc on ferme :p

**Comment by ubiquando** [comment]
oui, en fait je pense finalement juste faire des redirections apache. On pourrait ajouter un bouton qui ajoute une redirection vers la collection (ou catégorie) dans le .htaccess
