### ISSUE TITLE
bug install metas-plus

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite#21]
dans la v2 de metas-plus, il n'y a plus de metasplus-article.html
=> on a mis "dist" et ça marche...

**Comment by ubiquando** [comment]
geodiversite/head/article.html

**Comment by brunob** [comment]
Oui, c'est une adaptation pour la v2 de geodiv cf https://github.com/geodiversite/geodiversite/commit/d0823528fbdef4bdb723437080b3616fdf5d2021

Bref, il faut que tu travailles avec la v2, la v1 qui est dans master pour l'instant passera en archive bientôt.
