### ISSUE TITLE
Erreur lecture imagecreatefromjpeg

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite#22]
sur 2 install différentes, bug sur la page d'accueil au niveau de l'image :
Erreur lecture imagecreatefromjpeg local/cache-gd2/8c/....
De façon un peu aléatoire, pbm de cache.
vider le cache ne résout pas forcément.
php 7.28/windows pour l'un, php 7.0 debian pour l'autre.

**Comment by brunob** [comment]
J'ai cru l'observer aussi, je pense que ça vient de la taille des images demandées pour les vignettes que j'ai augmenté pour la v2 (donc un bug de SPIP possiblement), mais je ne l'ai jamais vu en utilisant convert comme moteur de génération de vignettes.

**Comment by ubiquando** [comment]
en effet, ça marche mieux avec convert

**Comment by brunob** [comment]
Je n'ai plus observé le bug depuis un moment, on ferme ?

**Comment by ubiquando** [comment]
je l'ai revu récemment, mais c'est une version dont le spip n'est pas à jour, alors je suis revenu à convert et ça remarche.
Juste un truc bizarre avec des grosses photos verticales dont la vignette arrive horizontale, mais c'est un autre sujet (convert ou gd2pareil)...

**Comment by brunob** [comment]
Oui pour "la rotation" des images c'est bien un autre problème cf https://git.spip.net/spip/filtres_images/issues/4546 :)

Peut-être qu'un petit ajout dans le README (ou la doc si un jour quelqu'un s'y colle ^^) ferait l'affaire pour la recommandation d'utiliser convert ?

**Comment by brunob** [comment]
@ubiquando il en est où ton projet de documentation cf https://contrib.spip.net/ecrire/?exec=article&id_article=5441 ? Je vois que tu y mentionnes convert, donc on va dire qu'on peut fermer le ticket ici.
