### ISSUE TITLE
Refactoring de la page d'upload

### ISSUE THREAD

**Issue by brunob** [geodiversite/geodiversite#27]
Gros chantier en perspective... deux options : 

1. mettre à jour emballe_medias pour le brancher sur bigup
2. reprendre le code de la page d'upload pour se passer d'emballe_medias (ainsi que diogène)

La première piste est intéressante car elle permet de rester de minimiser le travail côté upload, mais ça implique pas mal de travail pour adapter emballe_medias à bigub cf https://git.spip.net/spip-contrib-extensions/emballe_medias/src/branch/master/inclure/upload_formulaire.html

J'ai déjà proposé de retirer la fonctionnalité obsolète d'upload swf par ici https://git.spip.net/spip-contrib-extensions/emballe_medias/issues/2 mais ça n'est qu'une petite brique du chantier qu'il y a à mener.

De plus, cela implique de maintenir le code de toutes la collection de plugins liés à l'upload : emballe_medias, diogène et ses sous modules, et emballe_medias_collections. Hors, ces plugins ne sont plus maintenus à ce jour, et geodiv est le dernier projet à les utiliser puisque mediaspip est à l'abandon....

Même si ça me fait mal de ne plus utiliser le pot commun, ça me semble intenable de m'engager à maintenir tout ça :\

La seconde piste permettrait de se débarrasser d'emballe_medias, diogène et ses sous modules. Ainsi on minimise l'effort de maintenance, et on peut plus facilement assurer le portage de geodiv vers SPIP 4.

Par contre, il faudrait recoder un plugin de collections, car emballe_medias_collections nécessite emballe_medias & diogène. Ça ne demanderait pas trop de travail, car à l'époque on le faisait déjà en se basant sur les grappes, et s'il faut on pourra recoder ça au propre dans https://github.com/geodiversite/geodiversite_albums

L'essentiel du code à récupérer d'emballe_medias est dans https://git.spip.net/spip-contrib-extensions/emballe_medias/src/branch/master/action/emballe_medias_upload.php

Il faudra aussi penser à reprendre les items de configuration `ecrire/?exec=configurer_emballe_medias` pour permettre de définir les extensions de fichiers autorisés à l'upload.

V'là le topo, c'est encore à affiner.

----

Quelques liens à propos de bigup :

- https://contrib.spip.net/Complement-de-documentation-Bigup
- https://git.spip.net/spip/bigup/wiki/Fonctionnement-technique

----

TODO en vrac : 

- [x] prise en charge des champs extras
- [x] récupérer l'article en cours de rédaction dans le secteur des médias
- [x] ajouter un js pour vérifier le quota d'upload avant de lancer bigup
- [x] ajouter un js pour autovalider le form et passer à l'étape 2 une fois l'upload de bigup terminé
- [x] permettre de supprimer le document après upload
- [x] géolocalisation à partir des exifs, délier le point lié au document et le lier à l'article comme cf https://git.spip.net/spip-contrib-extensions/diogene_geo/src/branch/master/diogene_geo_pipelines.php#L326
- [x] définir une liste d''extensions autorisées (dans la conf ou un define) et l'afficher et l'utiliser dans la saisie bigup / si on souhaite mettre en place une config pour ça plus tard on pourra s'inspirer de https://git.spip.net/spip-contrib-extensions/emballe_medias/src/branch/master/formulaires/configurer_emballe_medias_fichiers.html
- [x] vérifier que la licence par défaut appliquée dans la conf est bien prise en compte
- [x] supprimer `geol_balades_diogene_charger()` dans https://github.com/geodiversite/geodiversite_balades/blob/master/geol_balades_pipelines.php#L32

**Comment by brunob** [comment]
Pour le formulaire d'upload `#FORMULAIRE_EDITER_MEDIA` on peut partir sur un CVT en deux étapes : upload du media + renseignement des infos de l'article.

Trois cas de figure sont à prévoir : 

- nouveau média
- nouveau média avec un article en cours de rédaction présent
- média existant avec doc présent (avec possibilité de supprimer le doc et donc de revenir à l'étape 1)

À l'étape 1, si on a un article existant, il faudra peut-être reproduire ce que fait emballes_medias ici https://git.spip.net/spip-contrib-extensions/emballe_medias/src/branch/master/inclure/upload_formulaire.html#L18 afin de vérifier que l'auteur n'a pas déjà uploadé un document sur l'article depuis un autre onglet.

**Comment by brunob** [comment]
:timer_clock: 3.5

**Comment by ubiquando** [comment]
salut, pas vraiment d'avis qui puisse être utile, juste un encouragement sincère, c'est une bonne idée de rafraîchir tout ça !
