### ISSUE TITLE
admin collections depuis l'espace public

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite#40]
- Il semble qu'on ne puisse pas "administrer" une collection "publique" : impossible donc d'en faire une balade ; est-ce voulu ?
- on ne peut plus rendre privée une collection publique... ok ça peut se comprendre.
- ça me semblerait intéressant d'afficher quelque part si cette collection est publique ou privée (trouvé, c'est l'icône, je documente).
- pas évident de trouver comment ajouter un media à une collection publique d'un autre auteur => j'ai trouvé, je l'ajoute à la doc

**Comment by brunob** [comment]
> Il semble qu'on ne puisse pas "administrer" une collection "publique" : impossible donc d'en faire une balade ; est-ce voulu ?

Oui, une balade est forcément perso, donc on ne permet pas de passer une collection coop en balade.
