### ISSUE TITLE
tags inaccessible aux admins

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite#42]
Les admins auraient-ils moins de droits que les auteurs ?...
Sur 2 installations différentes, le bouton pour ajouter/modifier des tags n'apparaît pas sur la page media, même sur les media dont on est l'auteur.
bug ou feature ? Ou bug de ma config... ?

**Comment by brunob** [comment]
chez moi ça marche © tu est bien up de geodiv cf https://github.com/geodiversite/geodiversite/commit/f812f43f7ce75327037110950c14e15d6c5e9bb7 ?

**Comment by ubiquando** [comment]
ce n'était certes pas le cas, j'avais la version "officielle".
J'ai repris les versions git de tous les plugins geodiv, et le problème subsiste : les admins ne voient pas de bouton pour modifier les tags sur leurs propres publications..

**Comment by brunob** [comment]
Je viens de tester de nouveau, cette fois avec un compte admin non webmestre et ça fonctionne, ta versoin de geodiv ne doit pas être up ou tu as un pb dans ton install.

**Comment by ubiquando** [comment]
J'ai trouvé : il fallait configurer spipicious pour autoriser rédacteurs ET administrateurs à gérer des tags.
Désolé pour le bruit.
J'ajoute à la doc !

**Comment by brunob** [comment]
Ha mais c'est la conf par défaut, en fait il faut juste configurer spipicious, afin de renseigner le groupe de mots qu'il doit utiliser et ça le fait.
