### ISSUE TITLE
kml

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite#43]
J'essaie de voir comment afficher des kml autrement : l'affichage d'une grosse icône kml ne m'enthousiasme pas, sur la page d'accueil ou même sur les diverses galeries.
Plusieurs propositions, pour voir :
- pour un media image, si on ajoute un doc complémentaire kml, l'afficher sur la carte... possible ?
- pour un media kml, utiliser un media complémentaire (image) comme vignette ?
- associer un kml à une collection, et l'afficher sur la carte de la collection... bon je n'ai pas bien compris comment on affiche la carte d'une collection, et n'ai pas réussi à visualliser un kml associé à une balade.

**Comment by ubiquando** [comment]
- pour afficher un kml "complémentaire" sur la carte, oui, on peut modifier carte.html en ce sens (fait).
 => est-il envisageable que la fonction gis_static_map puisse intégrer/afficher un kml ?

**Comment by brunob** [comment]
Il faudrait améliorer le titre de ton ticket...

Perso, l'affichage de l'icone KML me va très bien, et tu dois pouvoir personnaliser la vignette du doc en le faisant depuis l'espace privé (cf vignette personnalisée du document), non ?

> associer un kml à une collection, et l'afficher sur la carte de la collection... bon je n'ai pas bien compris comment on affiche la carte d'une collection, et n'ai pas réussi à visualliser un kml associé à une balade.

Seules les collections de type balade affichent une carte.

>  => est-il envisageable que la fonction gis_static_map puisse intégrer/afficher un kml ?

Non, pas du tout.

PS : merci de faire un ticket par bug/évolution, sans quoi ça part dans tous les sens.

**Comment by ubiquando** [comment]
ok, désolé pour ce ticket brouillon. En fait, c'était plutôt une discussion sur l'usage du kml. Ce n'est probablement pas le bon endroit.

> Perso, l'affichage de l'icone KML me va très bien, et tu dois pouvoir personnaliser la vignette du doc en le faisant depuis l'espace privé (cf vignette personnalisée du document), non ?

certes, moi admin oui, mais les utilisateurs lambda non.

> Seules les collections de type balade affichent une carte.
De mon point de vue, cela a du sens de pouvoir afficher une carte correspondant à une collection, même hors balade.
Je l'ajouterai à mes squelettes.



> > => est-il envisageable que la fonction gis_static_map puisse intégrer/afficher un kml ?
> 
> Non, pas du tout.
J'aurais adoré pouvoir visualiser le kml sur la carte statique, dommage !

Et puis je n'arrive toujours pas à ajouter un kml à une balade mais je mets ça dans un autre ticket

**Comment by brunob** [comment]
> Et puis je n'arrive toujours pas à ajouter un kml à une balade mais je mets ça dans un autre ticket

Sur le bon repo alors https://github.com/geodiversite/geodiversite_balades :)

**Comment by brunob** [comment]
On ferme ici ?

**Comment by ubiquando** [comment]
oui oui !
- De mon côté j'ai modifié mon squelette "carte" pour afficher un kml d'un document complémentaire et ça me va
- je n'ai pas été plus loin pour afficher les kml sur la carte statique, mais ça m'intéresse (est-ce que j'ouvre un ticket pour ça ?)
- ta réparation du bug   https://github.com/geodiversite/geodiversite_balades/issues/3 a éclairci ma compréhension des collections et kml

MErci !

**Comment by brunob** [comment]
> je n'ai pas été plus loin pour afficher les kml sur la carte statique, mais ça m'intéresse (est-ce que j'ouvre un ticket pour ça ?)

C'est géré dans le plugin GIS, donc pas ici, mais amha ça n'est pas réalisable, à moins d'y passer un temps de ouf car il faudrait parser le KML et généré un image à partir de ces données pour ensuite la superposer à l'image généré par l'API de cartes statiques de GIS.
