### ISSUE TITLE
rotation des images

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite#45]
déjà évoqué dans le ticket #22 , les images verticales restent mal retournées sur les vignettes.
J'ai eu un espoir en voyant passer un message /discuter de spip à propos de https://git.spip.net/spip/spip/issues/5449
MAis :
- apparemment, ce n'est pas reporté dans spip 4.0.11
- même en reportant la modif pour voir dans mon dossier squelettes, cela ne règle pas le problème.

Autre idée ?

**Comment by brunob** [comment]
Ça sera réglé quand j'aurai terminé #37

**Comment by ubiquando** [comment]
spip mis à jour 4.1, plugins geodiversite* à jour, retest... hélas toujours une rotation mal venue des images verticales. :(

**Comment by brunob** [comment]
Tu peux partager l'image en question ici ?

**Comment by ubiquando** [comment]
![P4278902](https://user-images.githubusercontent.com/34694328/224311155-561fa564-90b0-4ea4-ad6d-e6e58d652996.JPG)

**Comment by brunob** [comment]
Ha mais c'est normal, https://git.spip.net/spip/spip/pulls/5450 n'a pas été reporté en 4.1... et je viens de tester avec le patch, ça fonctionne bien, on ferme donc.

**Comment by brunob** [comment]
Pour info, je viens de reporter le correctif dans la branche 4.1.

**Comment by ubiquando** [comment]
super, merci.
Le truc bizarre c'est que lorsque j'uploade mon image verticale, cela l'affiche horizontale... Mais maintenant, lorsque je la tourne (avec la flèche), c'est bon, et la vignette est correcte.
