### ISSUE TITLE
problème de sélection de point / geocoder 

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite#47]
Lorsqu'on géolocalise un media : 
- sélectionnons une adresse dans geocoder 
- mais l'adresse ne convenant pas, on choisit de sélectionner un point à la main
=> le dernier point est bien mémorisé pour LON et LAT, mais le champ GEO contient un POINT (x,y) où x et y sont les coordonnées issues du geocoder, et non celles du point cliqué.
Je ne sais pas si c'est un problème de geometries, de GIS, ou de geodiv.
On pourrait penser que ce n'est pas un bug, mais on mémorise quand même une donnée qui n'est pas cohérente avec le point retenu. Par exemple, on peut trouver un toponyme proche du nôtre, mais très loin du point qu'on recherche (c'est du vécu).
Pour moi, c'est un souci parce que j'utilise finalement la très, très belle fonction "geometrie_dans_polygone" de geometries, laquelle utilise les coordonnées du point de GEO prioritairement semble-t-il.

**Comment by brunob** [comment]
C'est un bug de gis_geometries je pense.

**Comment by brunob** [comment]
Je ne reproduis pas avec gis_geometries dans l'espace privé, je teste sur la page d'upload pour voir.

**Comment by brunob** [comment]
Idem avec geodiv depuis la page d'upload, si je fais ce que tu décris le champ `champ_geojson` est bien mis à jour lors du déplacement du point après geocoding. C'est bien ce champ que tu citais ?

**Comment by ubiquando** [comment]
je viens de retester, sur un geodiv "brut".
C'est le champ "geo" de la table "gis" qui garde les coordonnées du point cherché par le geocoder.

**Comment by brunob** [comment]
C'est donc lors de la modification d'un média existant ?

**Comment by ubiquando** [comment]
c'est dans tous les cas de création ou modification de point.
MAis j'ai vérifié, ce n'est qu'avec geodiv, parce que lorsqu'on crée un point directement dans l'espace ecrire, on ne peut pas modifier le positionnement d'un simple clic, il faut déplacer l'icône du point. Or dans geodiv il suffit d'un clic.
Dans le cas d'ajout d'un point via ecrire, la mise à jour après déplacement de l'icône donne dans "geo" un point correct, cohérent avec les  "lon" et "lat".

**Comment by brunob** [comment]
ha c'est au clic, voilà l'info qu'il me manquait, moi j'ai glissé le point et ça le fait bien

**Comment by ubiquando** [comment]
ah oui, en effet je viens de voir aussi qu'à la création, on peut aussi bouger l'icône... et que ça stocke la bonne info.
Remarque en passant : en modification, on ne peut pas la bouger, seul le clic fonctionne.

**Comment by brunob** [comment]
Et hop https://git.spip.net/spip-contrib-extensions/gis_geometries/issues/7
