### ISSUE TITLE
bug (?) pour gis_static_map 

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite#54]
Erreur d’exécution plugins/auto/geodiversite/inclure/rubrique_carte.html | File […]/plugins/auto/gis/v5.1.0/inc/staticmap.php Line 261 : imagecopy(): Argument #2 ($src_image) must be of type GdImage, bool given

Sur la page de la galerie, mais aussi sur les pages de la recherche.
C'est suite à la mise à jour des plugins geodiv*; spip 4.2.8, php8.2
Ce qui me surprend, c'est que sur une autre instance (même config, pas les mêmes données), pas de problème.
J'ai certes bien bidouillé mes squelettes, mais même lorsque j'enlève mes squelettes, le bug reste.
Bizarre, non ?

**Comment by brunob** [comment]
Le bug serait donc dans GIS plutôt que geodiv, mais avant de créer le ticket là bas il me faudrait un lien vers la page qui affiche l'erreur.

**Comment by ubiquando** [comment]
https://www.lespritdeslieux.fr/cat1
je peux te donner un accès au site si besoin

**Comment by brunob** [comment]
il faudrait débuguer ce qui se passe, en vérifiant ce qui se passe sur ces lignes :

https://git.spip.net/spip-contrib-extensions/gis/src/branch/master/inc/staticmap.php#L251
https://git.spip.net/spip-contrib-extensions/gis/src/branch/master/inc/staticmap.php#L253
https://git.spip.net/spip-contrib-extensions/gis/src/branch/master/inc/staticmap.php#L255

Je ferme le ticket ici, tu peux le recréer dans le repo GIS car c'est bien dans GIS qu'il y a un bug.

**Comment by ubiquando** [comment]
Juste pour info, j'avais signalé le bug ici : https://git.spip.net/spip-contrib-extensions/gis/-/issues/73
Et donc, après pas mal de tests, j'ai fini par vider le cache des images, et le bug a disparu. Désolé pour le dérangement.
