### ISSUE TITLE
bug install

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite#6]
même en suivant la doc...
en utilisant l'install via "install_geodiversite.sh",
j'ai beau créer un dossier lib à la racine, spip ne va pas chercher les libs correspondantes.
d'où les messages suivants :  
    Impossible d’activer le plugin ../plugins-dist/swfupload
        Ce plugin nécessite la librairie SWFUpload_v2.2.0.1_Core http://www.mediaspip.net/IMG/zip/swfupload_v2.2.0.1_core.zip
    Impossible d’activer le plugin ../plugins-dist/mediaspip_player
        Ce plugin nécessite la librairie jquery-mousewheel-3.1.4 https://github.com/brandonaaron/jquery-mousewheel/archive/3.1.4.zip

**Comment by brunob** [comment]
On en est où là dessus, on peut fermer ?
